import {
  ArrowLeft,
  Bot,
  Check,
  ChevronDown,
  CircleCheck,
  Clock3,
  Copy,
  Database,
  Edit3,
  Eye,
  EyeOff,
  Folder,
  Globe2,
  Info,
  KeyRound,
  Layers3,
  List,
  PanelLeft,
  Plus,
  Puzzle,
  RefreshCw,
  Search,
  Send,
  Settings,
  SlidersHorizontal,
  Sparkles,
  Star,
  Terminal,
  Trash2,
  WandSparkles,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

const icons = {
  abort: X,
  arrowLeft: ArrowLeft,
  bolt: Zap,
  chat: Bot,
  check: Check,
  checkCircle: CircleCheck,
  chevron: ChevronDown,
  clock: Clock3,
  close: X,
  code: Terminal,
  copy: Copy,
  db: Database,
  edit: Edit3,
  eye: Eye,
  eyeOff: EyeOff,
  folder: Folder,
  globe: Globe2,
  info: Info,
  key: KeyRound,
  list: List,
  model: Layers3,
  plus: Plus,
  puzzle: Puzzle,
  refresh: RefreshCw,
  search: Search,
  send: Send,
  settings: Settings,
  sidebar: PanelLeft,
  sliders: SlidersHorizontal,
  spark: Sparkles,
  star: Star,
  terminal: Terminal,
  trash: Trash2,
  wand: WandSparkles,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function Icon({ name, size = 18 }: { name: IconName; size?: number }) {
  const Component = icons[name];
  return <Component aria-hidden="true" size={size} strokeWidth={1.7} />;
}
